// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";

export class DataDeletion {
  static encode(message: DataDeletion, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.accountId);

    writer.uint32(18);
    writer.bytes(message.key);
  }

  static decode(reader: Reader, length: i32): DataDeletion {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DataDeletion();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.accountId = reader.string();
          break;

        case 2:
          message.key = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  accountId: string;
  key: Uint8Array;

  constructor(accountId: string = "", key: Uint8Array = new Uint8Array(0)) {
    this.accountId = accountId;
    this.key = key;
  }
}
