// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { PublicKey } from "./PublicKey";
import { AccessKey } from "./AccessKey";

export class AddKeyAction {
  static encode(message: AddKeyAction, writer: Writer): void {
    const publicKey = message.publicKey;
    if (publicKey !== null) {
      writer.uint32(10);
      writer.fork();
      PublicKey.encode(publicKey, writer);
      writer.ldelim();
    }

    const accessKey = message.accessKey;
    if (accessKey !== null) {
      writer.uint32(18);
      writer.fork();
      AccessKey.encode(accessKey, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): AddKeyAction {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new AddKeyAction();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.publicKey = PublicKey.decode(reader, reader.uint32());
          break;

        case 2:
          message.accessKey = AccessKey.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  publicKey: PublicKey | null;
  accessKey: AccessKey | null;

  constructor(
    publicKey: PublicKey | null = null,
    accessKey: AccessKey | null = null
  ) {
    this.publicKey = publicKey;
    this.accessKey = accessKey;
  }
}
