// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { BlockHeader } from "./BlockHeader";

export class Block {
  static encode(message: Block, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.author);

    const header = message.header;
    if (header !== null) {
      writer.uint32(18);
      writer.fork();
      BlockHeader.encode(header, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): Block {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new Block();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.author = reader.string();
          break;

        case 2:
          message.header = BlockHeader.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  author: string;
  header: BlockHeader | null;

  constructor(author: string = "", header: BlockHeader | null = null) {
    this.author = author;
    this.header = header;
  }
}
