// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";

export class CreateAccountNotAllowedErrorKind {
  static encode(
    message: CreateAccountNotAllowedErrorKind,
    writer: Writer
  ): void {
    writer.uint32(10);
    writer.string(message.accountId);

    writer.uint32(18);
    writer.string(message.predecessorId);
  }

  static decode(reader: Reader, length: i32): CreateAccountNotAllowedErrorKind {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CreateAccountNotAllowedErrorKind();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.accountId = reader.string();
          break;

        case 2:
          message.predecessorId = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  accountId: string;
  predecessorId: string;

  constructor(accountId: string = "", predecessorId: string = "") {
    this.accountId = accountId;
    this.predecessorId = predecessorId;
  }
}
