// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";

export class CreateAccountOnlyByRegistrarErrorKind {
  static encode(
    message: CreateAccountOnlyByRegistrarErrorKind,
    writer: Writer
  ): void {
    writer.uint32(10);
    writer.string(message.accountId);

    writer.uint32(18);
    writer.string(message.registrarAccountId);

    writer.uint32(26);
    writer.string(message.predecessorId);
  }

  static decode(
    reader: Reader,
    length: i32
  ): CreateAccountOnlyByRegistrarErrorKind {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new CreateAccountOnlyByRegistrarErrorKind();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.accountId = reader.string();
          break;

        case 2:
          message.registrarAccountId = reader.string();
          break;

        case 3:
          message.predecessorId = reader.string();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  accountId: string;
  registrarAccountId: string;
  predecessorId: string;

  constructor(
    accountId: string = "",
    registrarAccountId: string = "",
    predecessorId: string = ""
  ) {
    this.accountId = accountId;
    this.registrarAccountId = registrarAccountId;
    this.predecessorId = predecessorId;
  }
}
