// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { PublicKey } from "./PublicKey";

export class DeleteKeyAction {
  static encode(message: DeleteKeyAction, writer: Writer): void {
    const publicKey = message.publicKey;
    if (publicKey !== null) {
      writer.uint32(10);
      writer.fork();
      PublicKey.encode(publicKey, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): DeleteKeyAction {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new DeleteKeyAction();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.publicKey = PublicKey.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  publicKey: PublicKey | null;

  constructor(publicKey: PublicKey | null = null) {
    this.publicKey = publicKey;
  }
}
