// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { BigInt } from "./BigInt";

export class FunctionCallAction {
  static encode(message: FunctionCallAction, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.methodName);

    writer.uint32(18);
    writer.bytes(message.args);

    writer.uint32(24);
    writer.uint64(message.gas);

    const deposit = message.deposit;
    if (deposit !== null) {
      writer.uint32(34);
      writer.fork();
      BigInt.encode(deposit, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): FunctionCallAction {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new FunctionCallAction();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.methodName = reader.string();
          break;

        case 2:
          message.args = reader.bytes();
          break;

        case 3:
          message.gas = reader.uint64();
          break;

        case 4:
          message.deposit = BigInt.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  methodName: string;
  args: Uint8Array;
  gas: u64;
  deposit: BigInt | null;

  constructor(
    methodName: string = "",
    args: Uint8Array = new Uint8Array(0),
    gas: u64 = 0,
    deposit: BigInt | null = null
  ) {
    this.methodName = methodName;
    this.args = args;
    this.gas = gas;
    this.deposit = deposit;
  }
}
