// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

export enum FunctionCallErrorSer {
  CompilationError = 0,
  LinkError = 1,
  MethodResolveError = 2,
  WasmTrap = 3,
  WasmUnknownError = 4,
  HostError = 5,
  _EVMError = 6,
  ExecutionError = 7,
}
