// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

export enum InvalidTxError {
  InvalidAccessKeyError = 0,
  InvalidSignerId = 1,
  SignerDoesNotExist = 2,
  InvalidNonce = 3,
  NonceTooLarge = 4,
  InvalidReceiverId = 5,
  InvalidSignature = 6,
  NotEnoughBalance = 7,
  LackBalanceForState = 8,
  CostOverflow = 9,
  InvalidChain = 10,
  Expired = 11,
  ActionsValidation = 12,
  TransactionSizeExceeded = 13,
}
