// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { BigInt } from "./BigInt";

export class LackBalanceForStateErrorKind {
  static encode(message: LackBalanceForStateErrorKind, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.accountId);

    const balance = message.balance;
    if (balance !== null) {
      writer.uint32(18);
      writer.fork();
      BigInt.encode(balance, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): LackBalanceForStateErrorKind {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new LackBalanceForStateErrorKind();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.accountId = reader.string();
          break;

        case 2:
          message.balance = BigInt.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  accountId: string;
  balance: BigInt | null;

  constructor(accountId: string = "", balance: BigInt | null = null) {
    this.accountId = accountId;
    this.balance = balance;
  }
}
