// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { MerklePathItem } from "./MerklePathItem";

export class MerklePath {
  static encode(message: MerklePath, writer: Writer): void {
    const path = message.path;
    for (let i: i32 = 0; i < path.length; ++i) {
      writer.uint32(10);
      writer.fork();
      MerklePathItem.encode(path[i], writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): MerklePath {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new MerklePath();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.path.push(MerklePathItem.decode(reader, reader.uint32()));
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  path: Array<MerklePathItem>;

  constructor(path: Array<MerklePathItem> = []) {
    this.path = path;
  }
}
