// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { ReceiptValidationError } from "./ReceiptValidationError";

export class NewReceiptValidationErrorKind {
  static encode(message: NewReceiptValidationErrorKind, writer: Writer): void {
    writer.uint32(8);
    writer.int32(message.error);
  }

  static decode(reader: Reader, length: i32): NewReceiptValidationErrorKind {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new NewReceiptValidationErrorKind();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.error = reader.int32();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  error: ReceiptValidationError;

  constructor(error: ReceiptValidationError = 0) {
    this.error = error;
  }
}
