// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

export enum ReceiptValidationError {
  InvalidPredecessorId = 0,
  InvalidReceiverAccountId = 1,
  InvalidSignerAccountId = 2,
  InvalidDataReceiverId = 3,
  ReturnedValueLengthExceeded = 4,
  NumberInputDataDependenciesExceeded = 5,
  ActionsValidationError = 6,
}
