// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { CryptoHash } from "./CryptoHash";

export class ReceiptData {
  static encode(message: ReceiptData, writer: Writer): void {
    const dataId = message.dataId;
    if (dataId !== null) {
      writer.uint32(10);
      writer.fork();
      CryptoHash.encode(dataId, writer);
      writer.ldelim();
    }

    writer.uint32(18);
    writer.bytes(message.data);
  }

  static decode(reader: Reader, length: i32): ReceiptData {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ReceiptData();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.dataId = CryptoHash.decode(reader, reader.uint32());
          break;

        case 2:
          message.data = reader.bytes();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  dataId: CryptoHash | null;
  data: Uint8Array;

  constructor(
    dataId: CryptoHash | null = null,
    data: Uint8Array = new Uint8Array(0)
  ) {
    this.dataId = dataId;
    this.data = data;
  }
}
