// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";

export class SlashedValidator {
  static encode(message: SlashedValidator, writer: Writer): void {
    writer.uint32(10);
    writer.string(message.accountId);

    writer.uint32(16);
    writer.bool(message.isDoubleSign);
  }

  static decode(reader: Reader, length: i32): SlashedValidator {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SlashedValidator();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.accountId = reader.string();
          break;

        case 2:
          message.isDoubleSign = reader.bool();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  accountId: string;
  isDoubleSign: bool;

  constructor(accountId: string = "", isDoubleSign: bool = false) {
    this.accountId = accountId;
    this.isDoubleSign = isDoubleSign;
  }
}
