// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { BigInt } from "./BigInt";
import { PublicKey } from "./PublicKey";

export class StakeAction {
  static encode(message: StakeAction, writer: Writer): void {
    const stake = message.stake;
    if (stake !== null) {
      writer.uint32(10);
      writer.fork();
      BigInt.encode(stake, writer);
      writer.ldelim();
    }

    const publicKey = message.publicKey;
    if (publicKey !== null) {
      writer.uint32(18);
      writer.fork();
      PublicKey.encode(publicKey, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): StakeAction {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new StakeAction();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.stake = BigInt.decode(reader, reader.uint32());
          break;

        case 2:
          message.publicKey = PublicKey.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  stake: BigInt | null;
  publicKey: PublicKey | null;

  constructor(stake: BigInt | null = null, publicKey: PublicKey | null = null) {
    this.stake = stake;
    this.publicKey = publicKey;
  }
}
