// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { CryptoHash } from "./CryptoHash";

export class SuccessReceiptIdExecutionStatus {
  static encode(
    message: SuccessReceiptIdExecutionStatus,
    writer: Writer
  ): void {
    const id = message.id;
    if (id !== null) {
      writer.uint32(10);
      writer.fork();
      CryptoHash.encode(id, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): SuccessReceiptIdExecutionStatus {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new SuccessReceiptIdExecutionStatus();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.id = CryptoHash.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  id: CryptoHash | null;

  constructor(id: CryptoHash | null = null) {
    this.id = id;
  }
}
