// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { BigInt } from "./BigInt";

export class TransferAction {
  static encode(message: TransferAction, writer: Writer): void {
    const deposit = message.deposit;
    if (deposit !== null) {
      writer.uint32(10);
      writer.fork();
      BigInt.encode(deposit, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): TransferAction {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new TransferAction();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.deposit = BigInt.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  deposit: BigInt | null;

  constructor(deposit: BigInt | null = null) {
    this.deposit = deposit;
  }
}
