// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.25.0

import { Writer, Reader } from "as-proto/assembly";

export class ForeignMessage {
  static encode(message: ForeignMessage, writer: Writer): void {
    writer.uint32(8);
    writer.int32(message.c);

    writer.uint32(16);
    writer.int32(message.d);
  }

  static decode(reader: Reader, length: i32): ForeignMessage {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ForeignMessage();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.c = reader.int32();
          break;

        case 2:
          message.d = reader.int32();
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  c: i32;
  d: i32;

  constructor(c: i32 = 0, d: i32 = 0) {
    this.c = c;
    this.d = d;
  }
}
