// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { Block } from "../../sf/near/codec/v1/Block";

export class BlockAndReceipts {
  static encode(message: BlockAndReceipts, writer: Writer): void {
    const block = message.block;
    if (block !== null) {
      writer.uint32(10);
      writer.fork();
      Block.encode(block, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): BlockAndReceipts {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new BlockAndReceipts();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.block = Block.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  block: Block | null;

  constructor(block: Block | null = null) {
    this.block = block;
  }
}
