// Code generated by protoc-gen-as. DO NOT EDIT.
// Versions:
//   protoc-gen-as v1.3.0
//   protoc        v4.24.4

import { Writer, Reader } from "as-proto/assembly";
import { CryptoHash } from "../CryptoHash";

export class ActionReceiptProcessingStarted {
  static encode(message: ActionReceiptProcessingStarted, writer: Writer): void {
    const receiptHash = message.receiptHash;
    if (receiptHash !== null) {
      writer.uint32(10);
      writer.fork();
      CryptoHash.encode(receiptHash, writer);
      writer.ldelim();
    }
  }

  static decode(reader: Reader, length: i32): ActionReceiptProcessingStarted {
    const end: usize = length < 0 ? reader.end : reader.ptr + length;
    const message = new ActionReceiptProcessingStarted();

    while (reader.ptr < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          message.receiptHash = CryptoHash.decode(reader, reader.uint32());
          break;

        default:
          reader.skipType(tag & 7);
          break;
      }
    }

    return message;
  }

  receiptHash: CryptoHash | null;

  constructor(receiptHash: CryptoHash | null = null) {
    this.receiptHash = receiptHash;
  }
}
